Update ccclassroom.yml

diff --git a/.github/workflows/ccclassroom.yml b/.github/workflows/ccclassroom.yml
--- a/.github/workflows/ccclassroom.yml
+++ b/.github/workflows/ccclassroom.yml
@@ -7,14 +7,16 @@ env:
 jobs:
   build-and-send-test-results:
     runs-on: ubuntu-latest
+    timeout-minutes: 8
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
       - name: Set up JDK 17
-        uses: actions/setup-java@v1
+        uses: actions/setup-java@v3
         with:
+          distribution: 'adopt'
           java-version: 17
       - name: Build with Maven
-        run: mvn clean test || true # don't fail because we don't want students to receive workflow failure emails, if some tests fail.
+        run: mvn --batch-mode --no-transfer-progress clean test || true # don't fail because we don't want students to receive workflow failure emails, if some tests fail.
       - name: Inspect surefire files
         if: always() # even if there are failing tests, we want to output and send surefire reports to ccclassroom app.
         run: cat target/surefire-reports/*.txt || true
